
import { useRef, useState } from 'react';
import QRCode from 'react-qr-code';
import { toPng } from 'html-to-image';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

const QrToPdf = (props) => {
    const qrWrapperRef = useRef(null);
    const [url, setUrl] = useState(props.url);

    const generatePdfWithQr = async () => {
        if (!qrWrapperRef.current) return;

        try {
            const qrImageDataUrl = await toPng(qrWrapperRef.current);

            const pdfDoc = await PDFDocument.create();
            const page = pdfDoc.addPage([500, 600]);

            const qrImage = await pdfDoc.embedPng(qrImageDataUrl);
            const { width, height } = qrImage.scale(0.8);

            const font = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
            const smallFont = await pdfDoc.embedFont(StandardFonts.Helvetica);

            // Background color
            page.drawRectangle({
                x: 0,
                y: 0,
                width: page.getWidth(),
                height: page.getHeight(),
                color: rgb(0.92, 0.92, 0.92) // light gray
            });

            // Header text
            page.drawText("Below is your QR Code", {
                x: 125,
                y: 540,
                size: 22,
                font,
                color: rgb(0, 0, 0),
            });

            // Draw QR Image
            page.drawImage(qrImage, {
                x: (page.getWidth() - width) / 2,
                y: (page.getHeight() - height) / 2,
                width,
                height,
            });

            // Footer
            page.drawText("Generated by Chittaranjan Saha", {
                x: 165,
                y: 40,
                size: 12,
                font: smallFont,
                color: rgb(0, 0, 0),
            });

            const pdfBytes = await pdfDoc.save();
            const blob = new Blob([pdfBytes], { type: 'application/pdf' });
            const urlBlob = URL.createObjectURL(blob);

            const a = document.createElement('a');
            a.href = urlBlob;
            a.download = 'qr-code.pdf';
            a.click();
            URL.revokeObjectURL(urlBlob);

        } catch (error) {
            console.error('Error generating PDF:', error);
        }
    };

    return (
        <div className="min-h-screen bg-black flex items-center justify-center">
            <div className="w-full max-w-md bg-gray-900 rounded-2xl shadow-xl p-6 space-y-6">

                <h1 className="text-center text-2xl font-semibold text-white">
                    QR Code Generator
                </h1>

                <input
                    type="text"
                    className="w-full p-3 rounded-md bg-gray-800 text-white placeholder-gray-400 border border-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    placeholder="Enter URL for QR code"
                    value={url}
                    onChange={(e) => setUrl(e.target.value)}
                />

                <div className="flex items-center justify-center p-4">
                    <div
                        ref={qrWrapperRef}
                        className="bg-white p-4 rounded-md transition-transform duration-300 hover:scale-105 hover:shadow-2xl"
                    >
                        <QRCode value={url} size={160} />
                    </div>
                </div>

                <button
                    onClick={generatePdfWithQr}
                    className="w-full bg-blue-500 hover:bg-blue-800 text-white py-3 rounded-md font-medium transition"
                >
                    Generate PDF with QR Code
                </button>
            </div>
        </div>
    );
};

export default QrToPdf;
